hl.on("hyprland.start", function () 
  hl.exec_cmd("udiskie")
  hl.exec_cmd("nm-applet --indicator")
  hl.exec_cmd("waybar & hyprpaper & firefox")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
